### ISSUE TITLE
Not subtracting the fast ion density from ne in halo calc?

### ISSUE THREAD

**Issue by shaunhaskey** [D3DEnergetic/FIDASIM#102]
Should this line in the halo calculation:
https://github.com/D3DEnergetic/FIDASIM/blob/master/src/fidasim.f90#L5985
be changed from:
```
states = prob*plasma%denp
```
to:
```
states = prob*(plasma%denp - plasma%denf)
```
which is what it is in the dcx calculation....

Note in the halo calculation  L5952:
```
papprox(i,j,k)= tot_denn*(plasma%denp-plasma%denf)
```

**Comment by lstagner** [comment]
I have had this discussion with other people in the past. Remember the `denp` is the full ion density (thermal + fast) calculated via quasi-neutrality. In the DCX we only want to charge exchange with the thermal ions so we subtract out the fast-ions (charge exchange with fast ions is FIDA) . In the Halo calculation the a thermal neutral could charge exchange with either a fast or thermal ion so we leave `denp` as is.

**Comment by shaunhaskey** [comment]
@lstagner bit slow getting back to this.... you probably had this discussion with me. Thanks for the details.  So... for the halo calculation, is charge exchange/ionisation with fast ions explicitly included (i.e including the properties of the fast ions), or does setting (states = prob * denp) just mean that you make the simplification that the fast ions are just thermals because this is better than leaving out their interaction with the DCX neutrals completely?

For the papprox part at the beginning of the halo subroutine:
```
papprox(i,j,k)= tot_denn*(plasma%denp-plasma%denf)
```
should this also be: 
```
papprox(i,j,k)= tot_denn*(plasma%denp)
```
for the same reasoning that states=prob*denp?

**Comment by lstagner** [comment]
>does setting (states = prob * denp) just mean that you make the simplification that the fast ions are just thermals because this is better than leaving out their interaction with the DCX neutrals completely?

Yep. 

>For the papprox part at the beginning of the halo subroutine:
>
>```papprox(i,j,k)= tot_denn*(plasma%denp-plasma%denf)```
>should this also be:

> ```papprox(i,j,k)= tot_denn*(plasma%denp)```
>for the same reasoning that states=prob*denp?

Nope. `papprox` is used to determine how many particles are launched in each cell. For instance we don't launch any particles where there isn't any neutrals because they wouldn't contribute anyway. Now we could say "Launch N particles from every cell that has neutrals" and I would get the same answer (given enough MC particles).

But we can be a bit smarter about how we choose the the number launched in each cell. The number of particles launched is directly related to the Monte Carlo noise so in principle we would want to reduce the Monte Carlo noise in regions we think are important e.g. where there are a lot neutrals and where there are a lot of ions. Making `nlaunch` proportional to the product of the neutral and ion density makes it so that the signal produced by these cells have better Monte Carlo noise. 

This trick also allows us to use less Monte Carlo particles since we can get the same noise characteristics as uniform launching with fewer particles.
