### ISSUE TITLE
Problem with the instalation

### ISSUE THREAD

**Issue by Jose-Rueda** [D3DEnergetic/FIDASIM#132]
Hello, I'm trying to install FIDASIM and I've always the same problem. Make order does not work. 
I paste here my terminal:

jose@J ~/FIDASIM $ pwd
/home/jose/FIDASIM
jose@J ~/FIDASIM $ ls
FIDASIM-1.2.0.tar.gz
jose@J ~/FIDASIM $ tar -zxf FIDASIM-1.2.0.tar.gz
jose@J ~/FIDASIM $ cd FIDASIM-1.2.0
jose@J ~/FIDASIM/FIDASIM-1.2.0 $ pwd
/home/jose/FIDASIM/FIDASIM-1.2.0
jose@J ~/FIDASIM/FIDASIM-1.2.0 $ 
jose@J ~/FIDASIM/FIDASIM-1.2.0 $ export FIDASIM_DIR=/home/jose/FIDASIM/FIDASIM-1.2.0
jose@J ~/FIDASIM/FIDASIM-1.2.0 $ export FC=gfortran 
jose@J ~/FIDASIM/FIDASIM-1.2.0 $ export CC=gcc      
jose@J ~/FIDASIM/FIDASIM-1.2.0 $ export CXX=g++     
jose@J ~/FIDASIM/FIDASIM-1.2.0 $ export PATH=$FIDASIM_DIR/deps/hdf5/bin:$FIDASIM_DIR/lib/scripts:$PATH
jose@J ~/FIDASIM/FIDASIM-1.2.0 $ export IDL_PATH="+$FIDASIM_DIR:$IDL_PATH:<IDL_DEFAULT>"
jose@J ~/FIDASIM/FIDASIM-1.2.0 $ export PYTHONPATH=$FIDASIM_DIR/lib/python:$PYTHONPATH
jose@J ~/FIDASIM/FIDASIM-1.2.0 $ ulimit -s unlimited 
jose@J ~/FIDASIM/FIDASIM-1.2.0 $ source ~/.bashrc
jose@J ~/FIDASIM/FIDASIM-1.2.0 $ make
make[1]: se entra en el directorio '/home/jose/FIDASIM/FIDASIM-1.2.0/deps'

Building HDF5...
tar -zxvf /home/jose/FIDASIM/FIDASIM-1.2.0/deps/hdf5-1.8.16.tar.gz > /dev/null 2>&1
cd /home/jose/FIDASIM/FIDASIM-1.2.0/deps/hdf5-1.8.16; ./configure --prefix=/home/jose/FIDASIM/FIDASIM-1.2.0/deps/hdf5 --enable-fortran --enable-cxx > /dev/null 2>&1
makefile:6: fallo en las instrucciones para el objetivo 'hdf5'
make[1]: *** [hdf5] Error 1
make[1]: se sale del directorio '/home/jose/FIDASIM/FIDASIM-1.2.0/deps'
makefile:109: fallo en las instrucciones para el objetivo 'deps'
make: *** [deps] Error 2

Can someone help me?

**Comment by lstagner** [comment]
This is made difficult since the HDF5 build log wasn't saved (it is saved in the bugfix release I just made). Without that information I can just guess that you have not installed all the required dependencies. The following commands will install them
```bash
sudo apt-get update
sudo apt-get install build-essential
sudo apt-get install gfortran
sudo apt-get install zlib1g-dev
```
Make sure you run `make clean_all` before you compile to start on a clean slate.

If that doesn't solve your issue then you should download the latest release (which you should do anyway) and post the `deps/hdf5_build.log` file (using https://pastebin.com/ since the file can be quite large)

Also, you should set your environmental variables in your `.bashrc` file so that you don't have to reset them every time you start a terminal.

**Comment by Jose-Rueda** [comment]
It's working now. 
Thank you very much for the quick answer
All it's perfect now

**Comment by lstagner** [comment]
Great!

For my own records, could you tell me who you are working for (if you are working for someone), institution, and what you are planning use FIDASIM for?
