### ISSUE TITLE
TODO: Improve automatic passive grid creation 

### ISSUE THREAD

**Issue by lstagner** [D3DEnergetic/FIDASIM#167]
This is just a reminder to myself to fix how we create the passive grid. Right now we are reading in diagnostic geometry twice. This is inelegant and inefficient. To fix this we make `read_chords` and `read_npa` just read in the geometry and move any line-of-sight intersection/probability calculations into a `make_grids` subroutine that both makes the beam and passive grids and also does the line-of-sight/probability calculations.

**Comment by alvin-garcia** [comment]
Luke,

I like this idea.

The NC signal calculations need a cylindrical grid. I am wondering what the best approach would be. It is easy to imagine a hypothetical situation where the FIDA, NPA and NC diagnostics (possibly more in the future) cover the entire torus. Having one grid is obviously simpler and desirable. However, calculation time is longer because a lot of phi values are necessary to have good resolution.

What do you think?

**Comment by lstagner** [comment]
Simpler yes but very inefficient computationally. Something you may want to look into is having a separate grid for each diagnostic system.
