### ISSUE TITLE
New functional - possible?

### ISSUE THREAD

**Issue by BlehMaks** [D3DEnergetic/FIDASIM#174]
Dear FIDASIM team,

I have some suggestions/questions about additional functional.
1) There is relatively high contribution of cold neutrals (with energy ~ ion temperature) to the NPA signal on TCV. I thought if FIDASIM allows to calculate cold line for FIDA, may be it will be possible to implement calculation of cold neutrals' (with energy ~ ion temperature) contribution to NPA signal also. Is it so?
If the answer is positive, may I kindly ask you to implement it?
2) Is it possible to implement calculation of passive FIDA and NPA signals using weight function method?
3) Also, does description of additional functional of calculations (with calc_* switch 2) exist?

If described functional already exist, could you please show me, where I can find information about it?

Thank you in advance!
Best regards,
Maksim

**Comment by BlehMaks** [comment]
Thank you very much for consideration!
Sorry for disturbing you, but is there any answer on previous message?
Thank you in advance!

Best regards,
Maksim

**Comment by lstagner** [comment]
> There is relatively high contribution of cold neutrals (with energy ~ ion temperature) to the NPA signal on TCV. I thought if FIDASIM allows to calculate cold line for FIDA, may be it will be possible to implement calculation of cold neutrals' (with energy ~ ion temperature) contribution to NPA signal also. Is it so?
If the answer is positive, may I kindly ask you to implement it?

There are no plans to implement this functionality but feel free if you want to give it a shot.

>Is it possible to implement calculation of passive FIDA and NPA signals using weight function method?

Technically yes but it wouldn't be accurate since the measurement volume is not spatially localized. However that is only true for velocity-space weight functions. You can calculate passive orbit weight functions but that functionality is not implemented in FIDASIM. You would have to calculate them like I did in my thesis.

>Also, does description of additional functional of calculations (with calc_* switch 2) exist?

The `calc_*=2` switch is for advanced users most of the time it just means that some extra output was written to the file for example `calc_npa=2` outputs the particle's velocity and position that hit the npa detector. The exception to this is the `calc_fida_wght=2` switch which changes the calculation method. This is documented in the [user manual/website](http://d3denergetic.github.io/FIDASIM/page/02_physics/07_weights.html)
