### ISSUE TITLE
Question on weight function generation

### ISSUE THREAD

**Issue by mabaquero** [D3DEnergetic/FIDASIM#228]
Dear developers,
I work with the FIDA diagnostic in the TCV tokamak in Lausanne (Switzerland).

In a recent discussion with some colleagues, the question came up as to whether it is possible to use FIDASIM to *only* generate weight functions (i.e. forgetting about synthetic spectra). Naively, I would think that this should be possible by providing the different plasma, beam and geometry parameters but *no* fast-ion distribution. However, FIDASIM does not allow one to run it without providing a fast-ion distribution (from a quick attempt - maybe I am wrong?).

Is it possible to do this, or am I forgetting something important?

If it is possible, is there an easy way to configure FIDASIM to do it?
Do I need to come up with some dummy distribution?

Thanks a lot,
Marcelo Baquero-Ruiz

**Comment by lstagner** [comment]
Hello,

Technically, you need a fast-ion distribution to calculate the weight functions because there is a slight dependency on the distribution in the direct charge exchange (DCX) calculation when calculating the neutral beam density. That being said it is a rather weak dependency and doesn't really affect anything. So you can go ahead and just provide a distribution that is all zeros and things should work alright.

**Comment by mabaquero** [comment]
Thanks Luke! 
We will give it a try then.
