### ISSUE TITLE
definition of  radius in NPA Geometry Structure

### ISSUE THREAD

**Issue by rink2023** [D3DEnergetic/FIDASIM#268]
I am confused on the definition of  radius in NPA Geometry Structure.
The instruction said the definition is:
radius | Float64 | 1 | [nchan] | cm | Line of sight radius at midplane or tangency point
I can not understand the exact meaning of "Line of sight radius at midplane or tangency point".
Since the line of sight (LOS) coud be defined by two points a_cent and d_cent,  why we still need radius to define the LOS.

regards

**Comment by lstagner** [comment]
You are correct. The radius field isn't actually necessary for the calculation of NPA flux. It is used when printing out information about the chords during runtime but thats it. You could just set it all to zero and it would be fine. Its there because most people associate channels with where they are looking in the machines so it gives them a way to internally visualize the channels.
