### ISSUE TITLE
Discrepancy in the NPA neutral flux between FIDASIM3.0-dev and FIDASIM2.0

### ISSUE THREAD

**Issue by deyongl** [D3DEnergetic/FIDASIM#271]
There exists some discrepancy in the magnitude of the NPA neutral flux between the latest FIDASIM in GitHub and FIDASIM 2.0. It is found that the difference started to appear in the FIDASIM version after pull request 187. The simulation results before the pull request 187 agree well with FIDASIM2.0.
![image](https://github.com/D3DEnergetic/FIDASIM/assets/12468380/cb739bf0-3092-4a11-a8fd-dc63c5963069)

**Comment by lstagner** [comment]
I finally found the bug. Its now fixed on master. The issue was that the rate matrix calculation didn't correct for the fast-ion contribution. In #186 this was included in the `denp` variable but since we now provide `deni` which is just the thermal ions it was left out accidently when I updated the other instances of `denp`.
