### ISSUE TITLE
Unable to get sucessful run using gfiles produced by TRXPL on recent TRANSP runs of MAST-U - looking for workaround

### ISSUE THREAD

**Issue by ajackson135** [D3DEnergetic/FIDASIM#278]
# Preface
I have had this problem with both v3.0.0-dev and v2.0, but in the rest of this entry I will be referring to FIDASIM-2.0, to allow for some older runs I have done to be used as comparison.

# Current Issue
## FIDASIM failures
I have been unable to get a successful FIDASIM run when using TRANSP runs produced recently (within last few months), as opposed to some that I did over 1.5 years ago. To test this specifically, I recently performed a TRANSP run of a MAST-U shot, of which I also have a TRANSP run produced a while ago. I then used `extract_transp_geqdsk` on the output of both.

I then attempted to do FIDASIM runs with the following set of inputs:
- Old TRANSP run with gfile produced by TRXPL applied to old TRANSP run: run succeeds 
- New TRANSP run with gfile produced by TRXPL applied to new TRANSP run: run fails
- Old TRANSP run with gfile produced by TRXPL applied to new TRANSP run: run fails
- New TRANSP run with gfile produced by TRXPL applied to old TRANSP run: run succeeds

Pre-processing is fine, but the actual run then terminates, with the following error in the output log:

> GYRO_STEP: Gyro correction results in negative distances or too large shift:    2.0365480978454307

The final value varies run-to-run, but is greater than 2 in general.

## GEQDSK file issue
I believe that the problem may stem from some change that has been made to TRXPL between the old runs and the new runs. Below I show some plots of $\psi$ from each gfile, which I emphasize are of the same shot and time within the shot, but 2 separate TRANSP runs, which I think will help describe the problem:

### $\psi$ from old gfile:
![g45026 00363_from_old_TRANSP_run](https://github.com/D3DEnergetic/FIDASIM/assets/12069627/efcbe8c8-7e0d-4f0c-98fa-e6fda198b390)

### $\psi$ from new gfile:
![g45026 00363_from_new_TRANSP_run](https://github.com/D3DEnergetic/FIDASIM/assets/12069627/d2adb43b-867a-4697-84c8-8b199a810d96)

I have been in discussion with some people involved with TRXPL and have been told the following in regards to the equilibrium:

>In the previous version of trxpl, the solution has been extrapolated to SOL. I believe trxpl does not extrapolate it anymore because it treats the TRANSP output as it is from a free-boundary solver even when the fixed boundary TEQ solver is used. 

I have been told that this is to be fixed later, but I do not know when that is.

# Request for help and information
- Can anyone tell me precisely what the problem is with recent gfiles as opposed to the old ones?
- Is this an issue that others have seen with recent TRANSP runs at facilities other than MAST-U? I do not know how TRXPL is dealt with between facilities. 
- Is this a problem with TRANSP rather than TRXPL?
- I am trying to see if I can get access to an older version of TRXPL, to see if that is the issue. Does anyone do that here? Would it even work on a recent TRANSP run?
- Finally, is there some kind of workaround that I can do to allow me to actually run FIDASIM successfully?

**Comment by kudav** [comment]
I am running into similar issues but for different reasons as trxpl is no longer supported in the environment I'm working in. Good to know that it probably doesn't make sense right now to change that :) I'd expect this to be an issue with trxpl and not transp though, as far as I know the extrapolation is done in post-processing.
I should note that I'm not a FIDASIM developer, so take my advice with a grain of salt.
As for your issue, if you havent figured it out in the meantime (since it's been a while), The constant \phi outside the separatrix would cause the B_R and B_Z components calculated from it to be screwy (probably zero), and this will likely lead to the gyro step being calculated incorrectly as you experienced. I remember running into similar issues and could fix them by changing the 'flr' namelist parameter to something other than 2, however this will of course impact your accuracy a bit.

**Comment by ajackson135** [comment]
Hello,

Thank you for your response and help. I had forgotten I put in this issue! The people that maintain TRXPL in my environment were able to update it to solve my issue, so I now no longer have this issue. Thank you for giving me the context in why the error was occurring. I hope you are able to solve your issue as well.
