### ISSUE TITLE
Feature Request: Option to dump DCX (0th generation halo) neutral density

### ISSUE THREAD

**Issue by lstagner** [D3DEnergetic/FIDASIM#56]
Here is a snippet from an email conversation describing the issue. 

> Sorry I had thought you wanted the neutrals from the first generation halo (Deyong wanted this when he was testing FIDASIM's Halo model with TRANSP's)

>First lets define our terms (D_0 = Beam Neutral, D_th(+) = Thermal Ion, D_f(+) = Fast Ion)

>D_0 + D_f(+)          ->    D_0(+) + D_f           # FIDA Neutral (Produces FIDA light)
D_0 + D_th0(+)       ->    D_0(+) + D_th0       # DCX (0th Generation Halo) Neutral (Produces Halo light)
D_th0 + D_th1(+)    ->    D_th0(+) + D_th1    # 1st Generation Halo Neutral (Produces Halo light)
D_th1 + D_th2(+)    ->    D_th1(+) + D_th2    # 2nd Generation Halo Neutral (Produces Halo light)
...and so on

>FIDASIM writes writes out the (0th-Nth) neutrals into the halodens variable. The DCX(0th Generation Halo) neutrals are calculated during the dcx subroutine. Subsequent halo neutral generations are calculated in the halo subroutine. If you just want the DCX(0th Generation Halo) neutral density and spectra then you just have to comment out the call to the halo subroutine located here. If you want the 0th-Nth generation neutrals and spectra then you would change the number of iterations (1-N) the halo subroutine does.

I see no reason not to include an option to do this but this brings up a number of questions that need to be answered.

* Should we merge the functionality of the ```subroutine dcx``` with ```subroutine halo```. They both essentially do the same thing (with some minor differences that can be handled by a if statement)
* Should we dump the density for every generation or just the 0th? What about just dumping the ith generation?
* Should I start calling the 0th generation the 1st generation?

@bgrierson21 @shaunhaskey @geigerb

**Comment by deyongl** [comment]
To be consistent with TRANSP definition, we had better call halo neutrals from CX reaction between beam neutrals and thermal ions as the 1st generation halo neutrals.

I personally like the idea to dump the halo neutral density for i-th generation (it could be just one generation, or a few generations). When I first saw the discrepancy of halo neutral density from TRANSP and FIDAsim simulations, I wanted to figure out whether the discrepancy appeared in the 1st generation halos or higher generation halos. It seems to me it is not necessary to dump the halo neutral density for every generation.

I personally think it is ok to keep the subroutine DCX separately from subroutine HALO. It is simply because DCX(or first generation) halos are come from the CX reactions between beam neutrals and thermal ions, while the higher generation halos are generated by the CX reactions between their parent neutrals and thermal ions.

**Comment by shaunhaskey** [comment]
I agree, it would be very nice to provide a list of i's for dumping the data for the i-th generation. Do you think this data should be in .nc files (i.e {neutrals,spectrum}_{0,1,2,...}.nc) or added as entries in the existing files?

**Comment by lstagner** [comment]
After discussing this offline with @deyongl and Bill we have decided on a course of action.

* Create a switch to indicate which generations get dumped ```dump_halo_generation = [1,2,3]```
* Merge the ```dcx``` and ```halo``` subroutines (This will make the dumping of the halo generations easier)

There are some difficulties. While it is easy to separate out the neutrals at each generation the spectra is not. The spectra is calculated and stored inside the ```spectra``` routine. We will need to separate out the storage of the spectra from that routine. This will effect many routines. It especially affects the FIDA weight function calculation so we have to keep that in mind.

**Comment by lstagner** [comment]
Fixed in #64
