### ISSUE TITLE
Add JET Routines

### ISSUE THREAD

**Issue by lstagner** [D3DEnergetic/FIDASIM#58]
It was requested that we add JET routines. This was already partially implemented in the [ls/srs_bench](https://github.com/D3DEnergetic/FIDASIM/tree/ls/srs_bench) branch in commit 8c2cb0e319fadb8769b714229ac24baa761f76c1 but everything in that commit is hard coded.  A person more familiar with JET will have to make them more general.

**Comment by tkoskela** [comment]
I can probably help with that. The routines could/should be modified so that the equilibrium, plasma profiles and beam energy/fractions are read from the JET ppf database. Is the format of the inputs-structure fixed, or can you add new things? There are a couple of identifiers that are needed for accessing the database.

**Comment by lstagner** [comment]
PREFIDA checks for [these variables](https://github.com/D3DEnergetic/FIDASIM/blob/master/prefida.pro#L825). So long as your PREFIDA input file/structure has at least those variables everything should be fine.

**Comment by lstagner** [comment]
New version of FIDASIM  #64 doesn't use device routines. All prefida does now is check inputs and writes the input files. Device routines are the responsibility of the user
