### ISSUE TITLE
Need to expand the cross section tables to lower energy and lower plasma temperature

### ISSUE THREAD

**Issue by deyongl** [D3DEnergetic/FIDASIM#61]
The lower energy limit of CX cross section table is currently set as 0.5keV/amu. It is desirable to expand the cross section tables to lower energy and lower plasma temperature. I have two test runs for a NSTX discharge, one with the standard FIDAsim cross section tables and the other one with new cross section tables  expanded to much lower relative energy and plasma temperature (see Fig.1).  Figure 2  clearly shows halo neutral density is overestimated when using the standard cross section  tables. The beam neutral densities from two runs are the same. The reason is simply because E_rel  (in the order of plasma temperature, i.e. 600-800eV in this case) in the calculation of halo neutrals is smaller  than the lower energy limit of CX cross section table and sig*v term is overestimated.

![cx_cross_section](https://cloud.githubusercontent.com/assets/12468380/8674108/abb634c2-2a09-11e5-8426-a007d6ba8410.jpg)
Fig.1 Comparison of standard FIDAdim cross section tables and new expanded cross section tables.

![beam_halo_centerline](https://cloud.githubusercontent.com/assets/12468380/8673878/3655a560-2a08-11e5-8a44-59dd3db8b067.png)
Fig.2 Comparison of beam and halo neutral density along the neutral beam centerline. The dashed lines are from the run with standard FIDAsim cross section tables, while the sold line are from the run with expanded cross section tables.

**Comment by bgrierson21** [comment]
This is an important addition for the low temperature work I'm doing with my post-doc with the halo neutrals near the edge where the temperatures can become low.

**Comment by lstagner** [comment]
When we make the switch to netCDF or HDF5 tables I will expand them to lower energies.

**Comment by lstagner** [comment]
Ok so @deyongl sent me his changes to the tables and they are too large to be hosted on Github. This is what I suggest we do. 

1. Have the user generate the tables when installing FIDASIM so we no longer have to host the files.
2. Since it takes a super long time to write the tables I suggest transfering the table writing routines to fortran. 

This has the advantage of allowing us to calculate cross sections on the fly when we want to be super accurate.

@deyongl When using the extended tables how much ram is typically being used by fidasim?

**Comment by lstagner** [comment]
Fixed in #64
