### ISSUE TITLE
FIDASIM inputs and densities

### ISSUE THREAD

**Issue by shaunhaskey** [D3DEnergetic/FIDASIM#88]
@lstagner  The input profiles related to particle densities include n_e, Zeff, Z_imp (=6 for C) and a fast ion density profile. I assume that FIDASIM works out the Deuterium and Carbon density profiles assuming quasi-neutrality. So if there are only thermal deuterium (n_D), fast deuterium (n_f) and carbon (n_c) then:

Zeff n_e = n_f + n_D + 36 n_c
n_e = n_f + n_D + 6 n_c

So my question is... does FIDASIM assume that n_f =0 when calculating n_c and n_D in the above equations? Essentially I want to set n_f as a free parameter that I can change to try and get good agreement with the intensity of the thermal deuterium line and I am trying to decide the best way to do this.

**Comment by lstagner** [comment]
FIDASIM calculates the Ion density and Impurity density [here](https://github.com/D3DEnergetic/FIDASIM/blob/master/src/fidasim.f90#L2040)

As you can see it combines the thermal and fast deuterium(The DCX calculation takes this into account by subtracting out the fast deuterium density).

The intensity of the D-alpha light is roughly proportional to the deuterium density. So if you were to do an simulation with zero fast ion density you could derive an formula to give you the fast-ion density.

![codecogseqn](https://cloud.githubusercontent.com/assets/4305891/14726136/e4381db6-07d4-11e6-9d3c-0a3bf67f7df9.png)

**Comment by shaunhaskey** [comment]
Hi Luke, thanks for the reply. At the moment I am getting a nice negative fast ion density :-1: but there are lots of things I need to check. I am curious why the fast and thermal Deuterium densities are combined at the beginning? Does this mean for the beam stopping calculation the fast Deuteriums are only included as an increased thermal deuterium density? (i.e their large speed is not taken into account in the cross sections for the beam stopping?)

**Comment by lstagner** [comment]
>Does this mean for the beam stopping calculation the fast Deuteriums are only included as an increased thermal deuterium density? (i.e their large speed is not taken into account in the cross sections for the beam stopping?) 

Yes. The reason the fast-deuterium density and the thermal deuterium density is combined is because a beam neutral could interact with both except in the case of DCX which the beam just interacts with the thermals hence the fast deuterium density is subtracted out. 

However cross sections are only averaged over the thermal deuterium velocity distribution. The correct thing to do is to average over the fast deuterium velocity distribution as well as the thermal. The issue is the fast-ion distribution is not known until runtime which means we would have to compute the reaction rates on the fly which would be too time consuming. 

Assuming that the thermal density is much greater then the fast-deuterium density then you can (hopefully) neglect the fast deuterium component. I am not sure how well tested this assumption is.

**Comment by lstagner** [comment]
Did you get this to work?

**Comment by shaunhaskey** [comment]
You can close this issue if you want. I didn't manage to figure out why I was getting negative fast ion densities yet.... could be that they are not resolvable due to various uncertainties. I plan to keep working on this in the background, but feel free to close this issue.
