### ISSUE TITLE
Rejection method error

### ISSUE THREAD

**Issue by loikki** [D3DEnergetic/FIDASIM#92]
Hi,
I am having a problem when running a simulation, I am obtaining the following message "Rejection method found no solution!" and I do not know what to do in order to have a solution

**Comment by lstagner** [comment]
The old version of FIDASIM, used a [rejection sampling](https://en.wikipedia.org/wiki/Rejection_sampling) method in order to draw samples from the fast ion distribution function. This type of sampling scheme doesn't do so well when most of your probabilistic mass is concentrated into a small area of phase space such as a delta function. One way of getting around this limitation is to reduce the phase space area over which you are sampling thus increasing the likelihood of the rejection method succeeding. You do this using the `emin`,`emax`,`pmin`,`pmax` input settings. This however is a blunt tool since the bounds would be applied over all of space (R-Z) which is strictly wrong since since the pitch of a fast-ion changes over its orbit.

In the new version of FIDASIM we switched to using [Inverse transform sampling](https://en.wikipedia.org/wiki/Inverse_transform_sampling) for the FIDA simulation (NPA still uses rejection sampling for other reasons). This method of sampling can be a bit slower but it is guaranteed to draw a sample from the distribution.

So the best way to fix your problem is to download the new version using git. 
Check out the [getting started guide](http://d3denergetic.github.io/FIDASIM/page/01_getting_started.html) (This guide assumes v1.0.0 has been tagged but just ignore those instructions for now)

**Comment by lstagner** [comment]
Also if you are trying to run on a specific device I have basic routines for preparing input for [NSTX](https://github.com/D3DEnergetic/nstx-fidasim) and [DIII-D](https://github.com/D3DEnergetic/d3d-fidasim)

**Comment by lstagner** [comment]
@loikki 

Did you manage to resolve the issue? If you have any issues please let me know.

**Comment by lstagner** [comment]
@loikki 

I am going to close this issue by the end of the week. If you have had any issues or questions please let me know.

**Comment by loikki** [comment]
Sorry I forgot to answer.
When you wrote I did not have enough time to work on it, but now everything is alright. I am able to do what I want to do.

Thanks

**Comment by lstagner** [comment]
Can you remind me. What are you using FIDASIM for?

**Comment by loikki** [comment]
I am using it in order to make a verification of my own simple beam simulation

**Comment by lstagner** [comment]
OK If you are using the new version of FIDASIM you need to make sure that
your version is up to date. A few weeks ago I found a bug in the neutral
beam calculation.
https://github.com/D3DEnergetic/FIDASIM/commit/31d41330b3cf12575d20a36fdb689b3449220662

Also you may find it useful to set the calc_birth switch. It will dump a
list of neutral beam particle positions and velocities in cylindrical
coordinates.

**Comment by loikki** [comment]
Ok thank you very much
